### PR TITLE
Add shipment api

### PR DESCRIPTION
**Pull request by backendArchitect**

### CODE REVIEW

**Comment by zeelrupapara** [comment]
Everything is good in creating orders (creating shipment API) :+1: but it still 
I think there is something wrong with the schema-type generation in ninja_van

I'm taking about the `modules/connectors/ninja_van/karrio/schemas/ninja_van/` file that is generated based on json files

For example request is like this 
```json
// API payload
{
   "name_organization": "github"
}
```

Then **Expected** getting generated code in schama like below
```python
from attr import s
from typing import Optional, List
from jstruct import JStruct


@s(auto_attribs=True)
class Request:
    name_organization: Optional[str] = None
```

But current generated **Recived** code based on that json file is like below 
```python
from attr import s
from typing import Optional, List
from jstruct import JStruct


@s(auto_attribs=True)
class Request:
    nameorganization: Optional[str] = None
```
OR Getting this type sometime

```python
from attr import s
from typing import Optional, List
from jstruct import JStruct


@s(auto_attribs=True)
class Request:
    nameOrganization: Optional[str] = None
```

> You need to generate the expected output file and then might be ninja van works well with karrio

**Comment by backendArchitect** [comment]
I'm unsure on that because same thing is being done in sedle which is earlier suggested by DAN
What you suggest ??

**Comment by zeelrupapara** [comment]
Yes I'm also going to tell you that
It would help if you took ref from the sendle

> So, You need to regenerate all types and get the expected formats

**Comment by zeelrupapara** [comment]
@codeArtisanry Check if any parameters are there in the command to get the sendle kind of output
Or you can generate types from any AI model like chatGPT

**Comment by backendArchitect** [comment]
@zeelrupapara Updated

**Comment by backendArchitect** [comment]
Client id and secrets are in vault warden @deltasquare4

**Pull request merged**
